[pads.pc]
0 = "Start"
1 = "In Game"
2 = "Pause"
3 = "End"

[pads.cc]
12 = "D4"
13 = "D6"
14 = "D8"
15 = "D10"
16 = "D12"
17 = "D20"

[faders]
70 = "My Micro"
71 = "Music"
72 = "Application Audio Capture (PipeWire)"
